# enable Docker for the repository
options:
  docker: true
  size: 2x

# Start the pipeline
pipelines:
  default:
  - step:
      script: # Name the image and create a docker image
      - docker build -t "cbr_reporting/cbr_reporting:latest" . 
      - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD $DOCKER_SERVER
      - docker push cbr_reporting/cbr_reporting:latest
