# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm i @angular/cli
          - npm install -g bestzip
          - npm run build-prod
          - bestzip cbr-reporting.zip dist/cbr-reporting 
          - pipe: microsoft/azure-web-apps-deploy:1.0.2
            variables:
                  AZURE_APP_ID: $AZURE_APP_ID
                  AZURE_PASSWORD: $AZURE_PASSWORD
                  AZURE_TENANT_ID: $AZURE_TENANT_ID
                  AZURE_RESOURCE_GROUP: 'customer-success-pm'
                  AZURE_APP_NAME: 'cbr-reporting'
                  ZIP_FILE: 'cbr-reporting.zip'
                  # SLOT: 'string' # Optional.
                  DEBUG: 'true' # Optional.
